// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class CommandPB {
  private CommandPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *保留值，不用
     * </pre>
     *
     * <code>TBB_RESERVED = 0;</code>
     */
    TBB_RESERVED(0),
    /**
     * <pre>
     *任务推送
     * </pre>
     *
     * <code>NOTIFY_DISPATCH_TASK = 200;</code>
     */
    NOTIFY_DISPATCH_TASK(200),
    /**
     * <pre>
     *任务操作，包括抢单、取货、配送完成
     * </pre>
     *
     * <code>REQUEST_TASK_OPERATE = 201;</code>
     */
    REQUEST_TASK_OPERATE(201),
    /**
     * <pre>
     *请求任务详情
     * </pre>
     *
     * <code>REQUEST_TASK_DETAIL = 202;</code>
     */
    REQUEST_TASK_DETAIL(202),
    /**
     * <pre>
     *请求可抢任务列表
     * </pre>
     *
     * <code>REQUEST_TASK_LIST = 203;</code>
     */
    REQUEST_TASK_LIST(203),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *保留值，不用
     * </pre>
     *
     * <code>TBB_RESERVED = 0;</code>
     */
    public static final int TBB_RESERVED_VALUE = 0;
    /**
     * <pre>
     *任务推送
     * </pre>
     *
     * <code>NOTIFY_DISPATCH_TASK = 200;</code>
     */
    public static final int NOTIFY_DISPATCH_TASK_VALUE = 200;
    /**
     * <pre>
     *任务操作，包括抢单、取货、配送完成
     * </pre>
     *
     * <code>REQUEST_TASK_OPERATE = 201;</code>
     */
    public static final int REQUEST_TASK_OPERATE_VALUE = 201;
    /**
     * <pre>
     *请求任务详情
     * </pre>
     *
     * <code>REQUEST_TASK_DETAIL = 202;</code>
     */
    public static final int REQUEST_TASK_DETAIL_VALUE = 202;
    /**
     * <pre>
     *请求可抢任务列表
     * </pre>
     *
     * <code>REQUEST_TASK_LIST = 203;</code>
     */
    public static final int REQUEST_TASK_LIST_VALUE = 203;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    public static Command forNumber(int value) {
      switch (value) {
        case 0: return TBB_RESERVED;
        case 200: return NOTIFY_DISPATCH_TASK;
        case 201: return REQUEST_TASK_OPERATE;
        case 202: return REQUEST_TASK_DETAIL;
        case 203: return REQUEST_TASK_LIST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.CommandPB.getDescriptor().getEnumTypes().get(0);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Command)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto*\203\001\n\007Command\022\020\n\014TBB_RESER" +
      "VED\020\000\022\031\n\024NOTIFY_DISPATCH_TASK\020\310\001\022\031\n\024REQU" +
      "EST_TASK_OPERATE\020\311\001\022\030\n\023REQUEST_TASK_DETA" +
      "IL\020\312\001\022\026\n\021REQUEST_TASK_LIST\020\313\001B5\n(com.xin" +
      "guang.tubobo.msgprotocol.transferB\tComma" +
      "ndPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
