// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestTaskList.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class RequestTaskListPB {
  private RequestTaskListPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestTaskListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestTaskList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code RequestTaskList}
   */
  public  static final class RequestTaskList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestTaskList)
      RequestTaskListOrBuilder {
    // Use RequestTaskList.newBuilder() to construct.
    private RequestTaskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestTaskList() {
      latitude_ = 0D;
      longitude_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestTaskList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              latitude_ = input.readDouble();
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.internal_static_RequestTaskList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.internal_static_RequestTaskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.class, com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0D) {
        output.writeDouble(1, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(2, longitude_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList)) {
        return super.equals(obj);
      }
      com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList other = (com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getLatitude())
          == java.lang.Double.doubleToLongBits(
              other.getLatitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLongitude())
          == java.lang.Double.doubleToLongBits(
              other.getLongitude()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestTaskList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestTaskList)
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.internal_static_RequestTaskList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.internal_static_RequestTaskList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.class, com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.Builder.class);
      }

      // Construct using com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;

        longitude_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.internal_static_RequestTaskList_descriptor;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList getDefaultInstanceForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.getDefaultInstance();
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList build() {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList buildPartial() {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList result = new com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList) {
          return mergeFrom((com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList other) {
        if (other == com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestTaskList)
    }

    // @@protoc_insertion_point(class_scope:RequestTaskList)
    private static final com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList();
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestTaskList>
        PARSER = new com.google.protobuf.AbstractParser<RequestTaskList>() {
      public RequestTaskList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestTaskList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestTaskList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestTaskList> getParserForType() {
      return PARSER;
    }

    public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskListPB.RequestTaskList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestTaskList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestTaskList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RequestTaskList.proto\"6\n\017RequestTaskLi" +
      "st\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001B" +
      "=\n(com.xinguang.tubobo.msgprotocol.trans" +
      "ferB\021RequestTaskListPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestTaskList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestTaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestTaskList_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
