// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestTaskOperate.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class RequestTaskOperatePB {
  private RequestTaskOperatePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestTaskOperateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestTaskOperate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskNo = 1;</code>
     */
    java.lang.String getTaskNo();
    /**
     * <code>string taskNo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskNoBytes();

    /**
     * <code>.TaskOperateEnum operate = 2;</code>
     */
    int getOperateValue();
    /**
     * <code>.TaskOperateEnum operate = 2;</code>
     */
    com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum getOperate();
  }
  /**
   * Protobuf type {@code RequestTaskOperate}
   */
  public  static final class RequestTaskOperate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestTaskOperate)
      RequestTaskOperateOrBuilder {
    // Use RequestTaskOperate.newBuilder() to construct.
    private RequestTaskOperate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestTaskOperate() {
      taskNo_ = "";
      operate_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestTaskOperate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskNo_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              operate_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.internal_static_RequestTaskOperate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.internal_static_RequestTaskOperate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.class, com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.Builder.class);
    }

    public static final int TASKNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskNo_;
    /**
     * <code>string taskNo = 1;</code>
     */
    public java.lang.String getTaskNo() {
      java.lang.Object ref = taskNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskNo_ = s;
        return s;
      }
    }
    /**
     * <code>string taskNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNoBytes() {
      java.lang.Object ref = taskNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATE_FIELD_NUMBER = 2;
    private int operate_;
    /**
     * <code>.TaskOperateEnum operate = 2;</code>
     */
    public int getOperateValue() {
      return operate_;
    }
    /**
     * <code>.TaskOperateEnum operate = 2;</code>
     */
    public com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum getOperate() {
      com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum result = com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.valueOf(operate_);
      return result == null ? com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskNo_);
      }
      if (operate_ != com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.GRAB.getNumber()) {
        output.writeEnum(2, operate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskNo_);
      }
      if (operate_ != com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.GRAB.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, operate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate)) {
        return super.equals(obj);
      }
      com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate other = (com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate) obj;

      boolean result = true;
      result = result && getTaskNo()
          .equals(other.getTaskNo());
      result = result && operate_ == other.operate_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKNO_FIELD_NUMBER;
      hash = (53 * hash) + getTaskNo().hashCode();
      hash = (37 * hash) + OPERATE_FIELD_NUMBER;
      hash = (53 * hash) + operate_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestTaskOperate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestTaskOperate)
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.internal_static_RequestTaskOperate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.internal_static_RequestTaskOperate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.class, com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.Builder.class);
      }

      // Construct using com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskNo_ = "";

        operate_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.internal_static_RequestTaskOperate_descriptor;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate getDefaultInstanceForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.getDefaultInstance();
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate build() {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate buildPartial() {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate result = new com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate(this);
        result.taskNo_ = taskNo_;
        result.operate_ = operate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate) {
          return mergeFrom((com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate other) {
        if (other == com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate.getDefaultInstance()) return this;
        if (!other.getTaskNo().isEmpty()) {
          taskNo_ = other.taskNo_;
          onChanged();
        }
        if (other.operate_ != 0) {
          setOperateValue(other.getOperateValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object taskNo_ = "";
      /**
       * <code>string taskNo = 1;</code>
       */
      public java.lang.String getTaskNo() {
        java.lang.Object ref = taskNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskNoBytes() {
        java.lang.Object ref = taskNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder setTaskNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder clearTaskNo() {
        
        taskNo_ = getDefaultInstance().getTaskNo();
        onChanged();
        return this;
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder setTaskNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskNo_ = value;
        onChanged();
        return this;
      }

      private int operate_ = 0;
      /**
       * <code>.TaskOperateEnum operate = 2;</code>
       */
      public int getOperateValue() {
        return operate_;
      }
      /**
       * <code>.TaskOperateEnum operate = 2;</code>
       */
      public Builder setOperateValue(int value) {
        operate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.TaskOperateEnum operate = 2;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum getOperate() {
        com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum result = com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.valueOf(operate_);
        return result == null ? com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.TaskOperateEnum operate = 2;</code>
       */
      public Builder setOperate(com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.TaskOperateEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operate_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TaskOperateEnum operate = 2;</code>
       */
      public Builder clearOperate() {
        
        operate_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestTaskOperate)
    }

    // @@protoc_insertion_point(class_scope:RequestTaskOperate)
    private static final com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate();
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestTaskOperate>
        PARSER = new com.google.protobuf.AbstractParser<RequestTaskOperate>() {
      public RequestTaskOperate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestTaskOperate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestTaskOperate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestTaskOperate> getParserForType() {
      return PARSER;
    }

    public com.xinguang.tubobo.msgprotocol.transfer.RequestTaskOperatePB.RequestTaskOperate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestTaskOperate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestTaskOperate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030RequestTaskOperate.proto\032\025TaskOperateE" +
      "num.proto\"G\n\022RequestTaskOperate\022\016\n\006taskN" +
      "o\030\001 \001(\t\022!\n\007operate\030\002 \001(\0162\020.TaskOperateEn" +
      "umB@\n(com.xinguang.tubobo.msgprotocol.tr" +
      "ansferB\024RequestTaskOperatePBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.getDescriptor(),
        }, assigner);
    internal_static_RequestTaskOperate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestTaskOperate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestTaskOperate_descriptor,
        new java.lang.String[] { "TaskNo", "Operate", });
    com.xinguang.tubobo.msgprotocol.transfer.TaskOperateEnumPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
