// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseTaskList.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class ResponseTaskListPB {
  private ResponseTaskListPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseTaskListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseTaskList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> 
        getItemsList();
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch getItems(int index);
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    java.util.List<? extends com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResponseTaskList}
   */
  public  static final class ResponseTaskList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseTaskList)
      ResponseTaskListOrBuilder {
    // Use ResponseTaskList.newBuilder() to construct.
    private ResponseTaskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseTaskList() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseTaskList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.internal_static_ResponseTaskList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.internal_static_ResponseTaskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> items_;
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    public java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    public java.util.List<? extends com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .NotifyTaskDispatch items = 1;</code>
     */
    public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList)) {
        return super.equals(obj);
      }
      com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList other = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseTaskList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseTaskList)
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.internal_static_ResponseTaskList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.internal_static_ResponseTaskList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.Builder.class);
      }

      // Construct using com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.internal_static_ResponseTaskList_descriptor;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList getDefaultInstanceForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.getDefaultInstance();
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList build() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList buildPartial() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList result = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList) {
          return mergeFrom((com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList other) {
        if (other == com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder setItems(
          int index, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder setItems(
          int index, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder addItems(com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder addItems(
          int index, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder addItems(
          com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder addItems(
          int index, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public java.util.List<? extends com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.getDefaultInstance());
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.getDefaultInstance());
      }
      /**
       * <code>repeated .NotifyTaskDispatch items = 1;</code>
       */
      public java.util.List<com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatch.Builder, com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.NotifyTaskDispatchOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResponseTaskList)
    }

    // @@protoc_insertion_point(class_scope:ResponseTaskList)
    private static final com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList();
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseTaskList>
        PARSER = new com.google.protobuf.AbstractParser<ResponseTaskList>() {
      public ResponseTaskList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseTaskList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseTaskList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseTaskList> getParserForType() {
      return PARSER;
    }

    public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListPB.ResponseTaskList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseTaskList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseTaskList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ResponseTaskList.proto\032\030NotifyTaskDisp" +
      "atch.proto\"6\n\020ResponseTaskList\022\"\n\005items\030" +
      "\001 \003(\0132\023.NotifyTaskDispatchB>\n(com.xingua" +
      "ng.tubobo.msgprotocol.transferB\022Response" +
      "TaskListPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.getDescriptor(),
        }, assigner);
    internal_static_ResponseTaskList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseTaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseTaskList_descriptor,
        new java.lang.String[] { "Items", });
    com.xinguang.tubobo.msgprotocol.transfer.NotifyTaskDispatchPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
