// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseTaskListItem.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class ResponseTaskListItemPB {
  private ResponseTaskListItemPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseTaskListItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseTaskListItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>string senderAddress = 2;</code>
     */
    java.lang.String getSenderAddress();
    /**
     * <code>string senderAddress = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderAddressBytes();

    /**
     * <code>float senderDistance = 3;</code>
     */
    float getSenderDistance();

    /**
     * <code>string senderName = 7;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string receiverAddress = 8;</code>
     */
    java.lang.String getReceiverAddress();
    /**
     * <code>string receiverAddress = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiverAddressBytes();

    /**
     * <code>float receiverDistance = 9;</code>
     */
    float getReceiverDistance();

    /**
     * <code>string receiverName = 12;</code>
     */
    java.lang.String getReceiverName();
    /**
     * <code>string receiverName = 12;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>string receiverPhone = 13;</code>
     */
    java.lang.String getReceiverPhone();
    /**
     * <code>string receiverPhone = 13;</code>
     */
    com.google.protobuf.ByteString
        getReceiverPhoneBytes();

    /**
     * <code>string orderType = 14;</code>
     */
    java.lang.String getOrderType();
    /**
     * <code>string orderType = 14;</code>
     */
    com.google.protobuf.ByteString
        getOrderTypeBytes();

    /**
     * <code>float income = 15;</code>
     */
    float getIncome();

    /**
     * <code>float deliveryFee = 16;</code>
     */
    float getDeliveryFee();

    /**
     * <code>float tipFee = 17;</code>
     */
    float getTipFee();
  }
  /**
   * Protobuf type {@code ResponseTaskListItem}
   */
  public  static final class ResponseTaskListItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseTaskListItem)
      ResponseTaskListItemOrBuilder {
    // Use ResponseTaskListItem.newBuilder() to construct.
    private ResponseTaskListItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseTaskListItem() {
      orderId_ = "";
      senderAddress_ = "";
      senderDistance_ = 0F;
      senderName_ = "";
      receiverAddress_ = "";
      receiverDistance_ = 0F;
      receiverName_ = "";
      receiverPhone_ = "";
      orderType_ = "";
      income_ = 0F;
      deliveryFee_ = 0F;
      tipFee_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseTaskListItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderAddress_ = s;
              break;
            }
            case 29: {

              senderDistance_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverAddress_ = s;
              break;
            }
            case 77: {

              receiverDistance_ = input.readFloat();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverPhone_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              orderType_ = s;
              break;
            }
            case 125: {

              income_ = input.readFloat();
              break;
            }
            case 133: {

              deliveryFee_ = input.readFloat();
              break;
            }
            case 141: {

              tipFee_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.internal_static_ResponseTaskListItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.internal_static_ResponseTaskListItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderAddress_;
    /**
     * <code>string senderAddress = 2;</code>
     */
    public java.lang.String getSenderAddress() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string senderAddress = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderAddressBytes() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERDISTANCE_FIELD_NUMBER = 3;
    private float senderDistance_;
    /**
     * <code>float senderDistance = 3;</code>
     */
    public float getSenderDistance() {
      return senderDistance_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 7;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERADDRESS_FIELD_NUMBER = 8;
    private volatile java.lang.Object receiverAddress_;
    /**
     * <code>string receiverAddress = 8;</code>
     */
    public java.lang.String getReceiverAddress() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverAddress = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverAddressBytes() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERDISTANCE_FIELD_NUMBER = 9;
    private float receiverDistance_;
    /**
     * <code>float receiverDistance = 9;</code>
     */
    public float getReceiverDistance() {
      return receiverDistance_;
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 12;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>string receiverName = 12;</code>
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERPHONE_FIELD_NUMBER = 13;
    private volatile java.lang.Object receiverPhone_;
    /**
     * <code>string receiverPhone = 13;</code>
     */
    public java.lang.String getReceiverPhone() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverPhone = 13;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverPhoneBytes() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 14;
    private volatile java.lang.Object orderType_;
    /**
     * <code>string orderType = 14;</code>
     */
    public java.lang.String getOrderType() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderType_ = s;
        return s;
      }
    }
    /**
     * <code>string orderType = 14;</code>
     */
    public com.google.protobuf.ByteString
        getOrderTypeBytes() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INCOME_FIELD_NUMBER = 15;
    private float income_;
    /**
     * <code>float income = 15;</code>
     */
    public float getIncome() {
      return income_;
    }

    public static final int DELIVERYFEE_FIELD_NUMBER = 16;
    private float deliveryFee_;
    /**
     * <code>float deliveryFee = 16;</code>
     */
    public float getDeliveryFee() {
      return deliveryFee_;
    }

    public static final int TIPFEE_FIELD_NUMBER = 17;
    private float tipFee_;
    /**
     * <code>float tipFee = 17;</code>
     */
    public float getTipFee() {
      return tipFee_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
      }
      if (!getSenderAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderAddress_);
      }
      if (senderDistance_ != 0F) {
        output.writeFloat(3, senderDistance_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, senderName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receiverAddress_);
      }
      if (receiverDistance_ != 0F) {
        output.writeFloat(9, receiverDistance_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, receiverName_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, receiverPhone_);
      }
      if (!getOrderTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, orderType_);
      }
      if (income_ != 0F) {
        output.writeFloat(15, income_);
      }
      if (deliveryFee_ != 0F) {
        output.writeFloat(16, deliveryFee_);
      }
      if (tipFee_ != 0F) {
        output.writeFloat(17, tipFee_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
      }
      if (!getSenderAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderAddress_);
      }
      if (senderDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, senderDistance_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, senderName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, receiverAddress_);
      }
      if (receiverDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, receiverDistance_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, receiverName_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, receiverPhone_);
      }
      if (!getOrderTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, orderType_);
      }
      if (income_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, income_);
      }
      if (deliveryFee_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, deliveryFee_);
      }
      if (tipFee_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, tipFee_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem)) {
        return super.equals(obj);
      }
      com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem other = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem) obj;

      boolean result = true;
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && getSenderAddress()
          .equals(other.getSenderAddress());
      result = result && (
          java.lang.Float.floatToIntBits(getSenderDistance())
          == java.lang.Float.floatToIntBits(
              other.getSenderDistance()));
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getReceiverAddress()
          .equals(other.getReceiverAddress());
      result = result && (
          java.lang.Float.floatToIntBits(getReceiverDistance())
          == java.lang.Float.floatToIntBits(
              other.getReceiverDistance()));
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getReceiverPhone()
          .equals(other.getReceiverPhone());
      result = result && getOrderType()
          .equals(other.getOrderType());
      result = result && (
          java.lang.Float.floatToIntBits(getIncome())
          == java.lang.Float.floatToIntBits(
              other.getIncome()));
      result = result && (
          java.lang.Float.floatToIntBits(getDeliveryFee())
          == java.lang.Float.floatToIntBits(
              other.getDeliveryFee()));
      result = result && (
          java.lang.Float.floatToIntBits(getTipFee())
          == java.lang.Float.floatToIntBits(
              other.getTipFee()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + SENDERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getSenderAddress().hashCode();
      hash = (37 * hash) + SENDERDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSenderDistance());
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + RECEIVERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverAddress().hashCode();
      hash = (37 * hash) + RECEIVERDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getReceiverDistance());
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + RECEIVERPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverPhone().hashCode();
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderType().hashCode();
      hash = (37 * hash) + INCOME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getIncome());
      hash = (37 * hash) + DELIVERYFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDeliveryFee());
      hash = (37 * hash) + TIPFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTipFee());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseTaskListItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseTaskListItem)
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.internal_static_ResponseTaskListItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.internal_static_ResponseTaskListItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.Builder.class);
      }

      // Construct using com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderId_ = "";

        senderAddress_ = "";

        senderDistance_ = 0F;

        senderName_ = "";

        receiverAddress_ = "";

        receiverDistance_ = 0F;

        receiverName_ = "";

        receiverPhone_ = "";

        orderType_ = "";

        income_ = 0F;

        deliveryFee_ = 0F;

        tipFee_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.internal_static_ResponseTaskListItem_descriptor;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem getDefaultInstanceForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.getDefaultInstance();
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem build() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem buildPartial() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem result = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem(this);
        result.orderId_ = orderId_;
        result.senderAddress_ = senderAddress_;
        result.senderDistance_ = senderDistance_;
        result.senderName_ = senderName_;
        result.receiverAddress_ = receiverAddress_;
        result.receiverDistance_ = receiverDistance_;
        result.receiverName_ = receiverName_;
        result.receiverPhone_ = receiverPhone_;
        result.orderType_ = orderType_;
        result.income_ = income_;
        result.deliveryFee_ = deliveryFee_;
        result.tipFee_ = tipFee_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem) {
          return mergeFrom((com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem other) {
        if (other == com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem.getDefaultInstance()) return this;
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getSenderAddress().isEmpty()) {
          senderAddress_ = other.senderAddress_;
          onChanged();
        }
        if (other.getSenderDistance() != 0F) {
          setSenderDistance(other.getSenderDistance());
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReceiverAddress().isEmpty()) {
          receiverAddress_ = other.receiverAddress_;
          onChanged();
        }
        if (other.getReceiverDistance() != 0F) {
          setReceiverDistance(other.getReceiverDistance());
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getReceiverPhone().isEmpty()) {
          receiverPhone_ = other.receiverPhone_;
          onChanged();
        }
        if (!other.getOrderType().isEmpty()) {
          orderType_ = other.orderType_;
          onChanged();
        }
        if (other.getIncome() != 0F) {
          setIncome(other.getIncome());
        }
        if (other.getDeliveryFee() != 0F) {
          setDeliveryFee(other.getDeliveryFee());
        }
        if (other.getTipFee() != 0F) {
          setTipFee(other.getTipFee());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderAddress_ = "";
      /**
       * <code>string senderAddress = 2;</code>
       */
      public java.lang.String getSenderAddress() {
        java.lang.Object ref = senderAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderAddressBytes() {
        java.lang.Object ref = senderAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder setSenderAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder clearSenderAddress() {
        
        senderAddress_ = getDefaultInstance().getSenderAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder setSenderAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderAddress_ = value;
        onChanged();
        return this;
      }

      private float senderDistance_ ;
      /**
       * <code>float senderDistance = 3;</code>
       */
      public float getSenderDistance() {
        return senderDistance_;
      }
      /**
       * <code>float senderDistance = 3;</code>
       */
      public Builder setSenderDistance(float value) {
        
        senderDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float senderDistance = 3;</code>
       */
      public Builder clearSenderDistance() {
        
        senderDistance_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 7;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverAddress_ = "";
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public java.lang.String getReceiverAddress() {
        java.lang.Object ref = receiverAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverAddressBytes() {
        java.lang.Object ref = receiverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder setReceiverAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder clearReceiverAddress() {
        
        receiverAddress_ = getDefaultInstance().getReceiverAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder setReceiverAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverAddress_ = value;
        onChanged();
        return this;
      }

      private float receiverDistance_ ;
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public float getReceiverDistance() {
        return receiverDistance_;
      }
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public Builder setReceiverDistance(float value) {
        
        receiverDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public Builder clearReceiverDistance() {
        
        receiverDistance_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>string receiverName = 12;</code>
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverPhone_ = "";
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public java.lang.String getReceiverPhone() {
        java.lang.Object ref = receiverPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverPhoneBytes() {
        java.lang.Object ref = receiverPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder setReceiverPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder clearReceiverPhone() {
        
        receiverPhone_ = getDefaultInstance().getReceiverPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder setReceiverPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderType_ = "";
      /**
       * <code>string orderType = 14;</code>
       */
      public java.lang.String getOrderType() {
        java.lang.Object ref = orderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderType = 14;</code>
       */
      public com.google.protobuf.ByteString
          getOrderTypeBytes() {
        java.lang.Object ref = orderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderType = 14;</code>
       */
      public Builder setOrderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderType = 14;</code>
       */
      public Builder clearOrderType() {
        
        orderType_ = getDefaultInstance().getOrderType();
        onChanged();
        return this;
      }
      /**
       * <code>string orderType = 14;</code>
       */
      public Builder setOrderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderType_ = value;
        onChanged();
        return this;
      }

      private float income_ ;
      /**
       * <code>float income = 15;</code>
       */
      public float getIncome() {
        return income_;
      }
      /**
       * <code>float income = 15;</code>
       */
      public Builder setIncome(float value) {
        
        income_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float income = 15;</code>
       */
      public Builder clearIncome() {
        
        income_ = 0F;
        onChanged();
        return this;
      }

      private float deliveryFee_ ;
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public float getDeliveryFee() {
        return deliveryFee_;
      }
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public Builder setDeliveryFee(float value) {
        
        deliveryFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public Builder clearDeliveryFee() {
        
        deliveryFee_ = 0F;
        onChanged();
        return this;
      }

      private float tipFee_ ;
      /**
       * <code>float tipFee = 17;</code>
       */
      public float getTipFee() {
        return tipFee_;
      }
      /**
       * <code>float tipFee = 17;</code>
       */
      public Builder setTipFee(float value) {
        
        tipFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float tipFee = 17;</code>
       */
      public Builder clearTipFee() {
        
        tipFee_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResponseTaskListItem)
    }

    // @@protoc_insertion_point(class_scope:ResponseTaskListItem)
    private static final com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem();
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseTaskListItem>
        PARSER = new com.google.protobuf.AbstractParser<ResponseTaskListItem>() {
      public ResponseTaskListItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseTaskListItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseTaskListItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseTaskListItem> getParserForType() {
      return PARSER;
    }

    public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskListItemPB.ResponseTaskListItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseTaskListItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseTaskListItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ResponseTaskListItem.proto\"\222\002\n\024Respons" +
      "eTaskListItem\022\017\n\007orderId\030\001 \001(\t\022\025\n\rsender" +
      "Address\030\002 \001(\t\022\026\n\016senderDistance\030\003 \001(\002\022\022\n" +
      "\nsenderName\030\007 \001(\t\022\027\n\017receiverAddress\030\010 \001" +
      "(\t\022\030\n\020receiverDistance\030\t \001(\002\022\024\n\014receiver" +
      "Name\030\014 \001(\t\022\025\n\rreceiverPhone\030\r \001(\t\022\021\n\tord" +
      "erType\030\016 \001(\t\022\016\n\006income\030\017 \001(\002\022\023\n\013delivery" +
      "Fee\030\020 \001(\002\022\016\n\006tipFee\030\021 \001(\002BB\n(com.xinguan" +
      "g.tubobo.msgprotocol.transferB\026ResponseT" +
      "askListItemPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResponseTaskListItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseTaskListItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseTaskListItem_descriptor,
        new java.lang.String[] { "OrderId", "SenderAddress", "SenderDistance", "SenderName", "ReceiverAddress", "ReceiverDistance", "ReceiverName", "ReceiverPhone", "OrderType", "Income", "DeliveryFee", "TipFee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
