// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TbbResultCode.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class TbbResultCodePB {
  private TbbResultCodePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code TbbResultCode}
   */
  public enum TbbResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TBB_SUCCESS = 0;</code>
     */
    TBB_SUCCESS(0),
    /**
     * <code>TBB_FAILURE = 1;</code>
     */
    TBB_FAILURE(1),
    /**
     * <pre>
     *内部服务错误
     * </pre>
     *
     * <code>TBB_SERVER_ERROR = 2;</code>
     */
    TBB_SERVER_ERROR(2),
    /**
     * <pre>
     *未登录
     * </pre>
     *
     * <code>TBB_UNLONGIN = 100;</code>
     */
    TBB_UNLONGIN(100),
    /**
     * <pre>
     *未认证
     * </pre>
     *
     * <code>TBB_UNAUTHED = 101;</code>
     */
    TBB_UNAUTHED(101),
    /**
     * <pre>
     *任务不可抢
     * </pre>
     *
     * <code>TBB_TASK_UN_GETABLE = 102;</code>
     */
    TBB_TASK_UN_GETABLE(102),
    /**
     * <pre>
     *押金不足
     * </pre>
     *
     * <code>TBB_INSUFFICIENT_DEPOSIT = 103;</code>
     */
    TBB_INSUFFICIENT_DEPOSIT(103),
    /**
     * <pre>
     *用户被冻结
     * </pre>
     *
     * <code>TBB_FROZEN = 104;</code>
     */
    TBB_FROZEN(104),
    /**
     * <pre>
     *用户认证失败
     * </pre>
     *
     * <code>TBB_VERIFY_FAIL = 105;</code>
     */
    TBB_VERIFY_FAIL(105),
    /**
     * <pre>
     *用户审核中
     * </pre>
     *
     * <code>TBB_VERIFYING = 106;</code>
     */
    TBB_VERIFYING(106),
    /**
     * <pre>
     *未找到用户
     * </pre>
     *
     * <code>TBB_NO_USER = 107;</code>
     */
    TBB_NO_USER(107),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TBB_SUCCESS = 0;</code>
     */
    public static final int TBB_SUCCESS_VALUE = 0;
    /**
     * <code>TBB_FAILURE = 1;</code>
     */
    public static final int TBB_FAILURE_VALUE = 1;
    /**
     * <pre>
     *内部服务错误
     * </pre>
     *
     * <code>TBB_SERVER_ERROR = 2;</code>
     */
    public static final int TBB_SERVER_ERROR_VALUE = 2;
    /**
     * <pre>
     *未登录
     * </pre>
     *
     * <code>TBB_UNLONGIN = 100;</code>
     */
    public static final int TBB_UNLONGIN_VALUE = 100;
    /**
     * <pre>
     *未认证
     * </pre>
     *
     * <code>TBB_UNAUTHED = 101;</code>
     */
    public static final int TBB_UNAUTHED_VALUE = 101;
    /**
     * <pre>
     *任务不可抢
     * </pre>
     *
     * <code>TBB_TASK_UN_GETABLE = 102;</code>
     */
    public static final int TBB_TASK_UN_GETABLE_VALUE = 102;
    /**
     * <pre>
     *押金不足
     * </pre>
     *
     * <code>TBB_INSUFFICIENT_DEPOSIT = 103;</code>
     */
    public static final int TBB_INSUFFICIENT_DEPOSIT_VALUE = 103;
    /**
     * <pre>
     *用户被冻结
     * </pre>
     *
     * <code>TBB_FROZEN = 104;</code>
     */
    public static final int TBB_FROZEN_VALUE = 104;
    /**
     * <pre>
     *用户认证失败
     * </pre>
     *
     * <code>TBB_VERIFY_FAIL = 105;</code>
     */
    public static final int TBB_VERIFY_FAIL_VALUE = 105;
    /**
     * <pre>
     *用户审核中
     * </pre>
     *
     * <code>TBB_VERIFYING = 106;</code>
     */
    public static final int TBB_VERIFYING_VALUE = 106;
    /**
     * <pre>
     *未找到用户
     * </pre>
     *
     * <code>TBB_NO_USER = 107;</code>
     */
    public static final int TBB_NO_USER_VALUE = 107;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TbbResultCode valueOf(int value) {
      return forNumber(value);
    }

    public static TbbResultCode forNumber(int value) {
      switch (value) {
        case 0: return TBB_SUCCESS;
        case 1: return TBB_FAILURE;
        case 2: return TBB_SERVER_ERROR;
        case 100: return TBB_UNLONGIN;
        case 101: return TBB_UNAUTHED;
        case 102: return TBB_TASK_UN_GETABLE;
        case 103: return TBB_INSUFFICIENT_DEPOSIT;
        case 104: return TBB_FROZEN;
        case 105: return TBB_VERIFY_FAIL;
        case 106: return TBB_VERIFYING;
        case 107: return TBB_NO_USER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TbbResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TbbResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TbbResultCode>() {
            public TbbResultCode findValueByNumber(int number) {
              return TbbResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.TbbResultCodePB.getDescriptor().getEnumTypes().get(0);
    }

    private static final TbbResultCode[] VALUES = values();

    public static TbbResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TbbResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TbbResultCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TbbResultCode.proto*\353\001\n\rTbbResultCode\022" +
      "\017\n\013TBB_SUCCESS\020\000\022\017\n\013TBB_FAILURE\020\001\022\024\n\020TBB" +
      "_SERVER_ERROR\020\002\022\020\n\014TBB_UNLONGIN\020d\022\020\n\014TBB" +
      "_UNAUTHED\020e\022\027\n\023TBB_TASK_UN_GETABLE\020f\022\034\n\030" +
      "TBB_INSUFFICIENT_DEPOSIT\020g\022\016\n\nTBB_FROZEN" +
      "\020h\022\023\n\017TBB_VERIFY_FAIL\020i\022\021\n\rTBB_VERIFYING" +
      "\020j\022\017\n\013TBB_NO_USER\020kB;\n(com.xinguang.tubo" +
      "bo.msgprotocol.transferB\017TbbResultCodePB" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
