// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MCProtocol.proto

package com.xinguang.msgprotocol.client.transfer;

public final class MCProtocolPB {
  private MCProtocolPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MCProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MCProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *消息类型，心跳，业务还是GPS上报
     * </pre>
     *
     * <code>.MsgType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类型，心跳，业务还是GPS上报
     * </pre>
     *
     * <code>.MsgType type = 2;</code>
     */
    com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType getType();

    /**
     * <pre>
     *区分哪个api业务系统与相应的app约定
     * </pre>
     *
     * <code>int32 command = 3;</code>
     */
    int getCommand();

    /**
     * <pre>
     *客户端识别码
     * </pre>
     *
     * <code>string clientSN = 4;</code>
     */
    java.lang.String getClientSN();
    /**
     * <pre>
     *客户端识别码
     * </pre>
     *
     * <code>string clientSN = 4;</code>
     */
    com.google.protobuf.ByteString
        getClientSNBytes();

    /**
     * <pre>
     *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
     * </pre>
     *
     * <code>string appClientID = 5;</code>
     */
    java.lang.String getAppClientID();
    /**
     * <pre>
     *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
     * </pre>
     *
     * <code>string appClientID = 5;</code>
     */
    com.google.protobuf.ByteString
        getAppClientIDBytes();

    /**
     * <pre>
     *服务端平台名如tubobo
     * </pre>
     *
     * <code>string platformID = 6;</code>
     */
    java.lang.String getPlatformID();
    /**
     * <pre>
     *服务端平台名如tubobo
     * </pre>
     *
     * <code>string platformID = 6;</code>
     */
    com.google.protobuf.ByteString
        getPlatformIDBytes();

    /**
     * <pre>
     *请求编号
     * </pre>
     *
     * <code>string reqID = 7;</code>
     */
    java.lang.String getReqID();
    /**
     * <pre>
     *请求编号
     * </pre>
     *
     * <code>string reqID = 7;</code>
     */
    com.google.protobuf.ByteString
        getReqIDBytes();

    /**
     * <pre>
     *区分是请求、响应或推送
     * </pre>
     *
     * <code>.Direction direction = 8;</code>
     */
    int getDirectionValue();
    /**
     * <pre>
     *区分是请求、响应或推送
     * </pre>
     *
     * <code>.Direction direction = 8;</code>
     */
    com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction getDirection();

    /**
     * <pre>
     *token值，需要登陆后才能
     * </pre>
     *
     * <code>string token = 9;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token值，需要登陆后才能
     * </pre>
     *
     * <code>string token = 9;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>bytes body = 16;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code MCProtocol}
   */
  public  static final class MCProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MCProtocol)
      MCProtocolOrBuilder {
    // Use MCProtocol.newBuilder() to construct.
    private MCProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MCProtocol() {
      version_ = "";
      type_ = 0;
      command_ = 0;
      clientSN_ = "";
      appClientID_ = "";
      platformID_ = "";
      reqID_ = "";
      direction_ = 0;
      token_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MCProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              command_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSN_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              appClientID_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              platformID_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              reqID_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              direction_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 130: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.internal_static_MCProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.internal_static_MCProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.class, com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *消息类型，心跳，业务还是GPS上报
     * </pre>
     *
     * <code>.MsgType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类型，心跳，业务还是GPS上报
     * </pre>
     *
     * <code>.MsgType type = 2;</code>
     */
    public com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType getType() {
      com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType result = com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.valueOf(type_);
      return result == null ? com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.UNRECOGNIZED : result;
    }

    public static final int COMMAND_FIELD_NUMBER = 3;
    private int command_;
    /**
     * <pre>
     *区分哪个api业务系统与相应的app约定
     * </pre>
     *
     * <code>int32 command = 3;</code>
     */
    public int getCommand() {
      return command_;
    }

    public static final int CLIENTSN_FIELD_NUMBER = 4;
    private volatile java.lang.Object clientSN_;
    /**
     * <pre>
     *客户端识别码
     * </pre>
     *
     * <code>string clientSN = 4;</code>
     */
    public java.lang.String getClientSN() {
      java.lang.Object ref = clientSN_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSN_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端识别码
     * </pre>
     *
     * <code>string clientSN = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClientSNBytes() {
      java.lang.Object ref = clientSN_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPCLIENTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object appClientID_;
    /**
     * <pre>
     *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
     * </pre>
     *
     * <code>string appClientID = 5;</code>
     */
    public java.lang.String getAppClientID() {
      java.lang.Object ref = appClientID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appClientID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
     * </pre>
     *
     * <code>string appClientID = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppClientIDBytes() {
      java.lang.Object ref = appClientID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appClientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORMID_FIELD_NUMBER = 6;
    private volatile java.lang.Object platformID_;
    /**
     * <pre>
     *服务端平台名如tubobo
     * </pre>
     *
     * <code>string platformID = 6;</code>
     */
    public java.lang.String getPlatformID() {
      java.lang.Object ref = platformID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *服务端平台名如tubobo
     * </pre>
     *
     * <code>string platformID = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformIDBytes() {
      java.lang.Object ref = platformID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQID_FIELD_NUMBER = 7;
    private volatile java.lang.Object reqID_;
    /**
     * <pre>
     *请求编号
     * </pre>
     *
     * <code>string reqID = 7;</code>
     */
    public java.lang.String getReqID() {
      java.lang.Object ref = reqID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求编号
     * </pre>
     *
     * <code>string reqID = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReqIDBytes() {
      java.lang.Object ref = reqID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 8;
    private int direction_;
    /**
     * <pre>
     *区分是请求、响应或推送
     * </pre>
     *
     * <code>.Direction direction = 8;</code>
     */
    public int getDirectionValue() {
      return direction_;
    }
    /**
     * <pre>
     *区分是请求、响应或推送
     * </pre>
     *
     * <code>.Direction direction = 8;</code>
     */
    public com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction getDirection() {
      com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction result = com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.valueOf(direction_);
      return result == null ? com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.UNRECOGNIZED : result;
    }

    public static final int TOKEN_FIELD_NUMBER = 9;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token值，需要登陆后才能
     * </pre>
     *
     * <code>string token = 9;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token值，需要登陆后才能
     * </pre>
     *
     * <code>string token = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 16;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (type_ != com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.HEART_BEAT.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (command_ != 0) {
        output.writeInt32(3, command_);
      }
      if (!getClientSNBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientSN_);
      }
      if (!getAppClientIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appClientID_);
      }
      if (!getPlatformIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, platformID_);
      }
      if (!getReqIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, reqID_);
      }
      if (direction_ != com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.PUSH.getNumber()) {
        output.writeEnum(8, direction_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, token_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(16, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (type_ != com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.HEART_BEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, command_);
      }
      if (!getClientSNBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientSN_);
      }
      if (!getAppClientIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appClientID_);
      }
      if (!getPlatformIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, platformID_);
      }
      if (!getReqIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, reqID_);
      }
      if (direction_ != com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.PUSH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, direction_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, token_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol)) {
        return super.equals(obj);
      }
      com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol other = (com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol) obj;

      boolean result = true;
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && type_ == other.type_;
      result = result && (getCommand()
          == other.getCommand());
      result = result && getClientSN()
          .equals(other.getClientSN());
      result = result && getAppClientID()
          .equals(other.getAppClientID());
      result = result && getPlatformID()
          .equals(other.getPlatformID());
      result = result && getReqID()
          .equals(other.getReqID());
      result = result && direction_ == other.direction_;
      result = result && getToken()
          .equals(other.getToken());
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      hash = (37 * hash) + CLIENTSN_FIELD_NUMBER;
      hash = (53 * hash) + getClientSN().hashCode();
      hash = (37 * hash) + APPCLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAppClientID().hashCode();
      hash = (37 * hash) + PLATFORMID_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformID().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqID().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + direction_;
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MCProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MCProtocol)
        com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.internal_static_MCProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.internal_static_MCProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.class, com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.Builder.class);
      }

      // Construct using com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = "";

        type_ = 0;

        command_ = 0;

        clientSN_ = "";

        appClientID_ = "";

        platformID_ = "";

        reqID_ = "";

        direction_ = 0;

        token_ = "";

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.internal_static_MCProtocol_descriptor;
      }

      public com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol getDefaultInstanceForType() {
        return com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.getDefaultInstance();
      }

      public com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol build() {
        com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol buildPartial() {
        com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol result = new com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol(this);
        result.version_ = version_;
        result.type_ = type_;
        result.command_ = command_;
        result.clientSN_ = clientSN_;
        result.appClientID_ = appClientID_;
        result.platformID_ = platformID_;
        result.reqID_ = reqID_;
        result.direction_ = direction_;
        result.token_ = token_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol) {
          return mergeFrom((com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol other) {
        if (other == com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        if (!other.getClientSN().isEmpty()) {
          clientSN_ = other.clientSN_;
          onChanged();
        }
        if (!other.getAppClientID().isEmpty()) {
          appClientID_ = other.appClientID_;
          onChanged();
        }
        if (!other.getPlatformID().isEmpty()) {
          platformID_ = other.platformID_;
          onChanged();
        }
        if (!other.getReqID().isEmpty()) {
          reqID_ = other.reqID_;
          onChanged();
        }
        if (other.direction_ != 0) {
          setDirectionValue(other.getDirectionValue());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *消息类型，心跳，业务还是GPS上报
       * </pre>
       *
       * <code>.MsgType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类型，心跳，业务还是GPS上报
       * </pre>
       *
       * <code>.MsgType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型，心跳，业务还是GPS上报
       * </pre>
       *
       * <code>.MsgType type = 2;</code>
       */
      public com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType getType() {
        com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType result = com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.valueOf(type_);
        return result == null ? com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型，心跳，业务还是GPS上报
       * </pre>
       *
       * <code>.MsgType type = 2;</code>
       */
      public Builder setType(com.xinguang.msgprotocol.client.transfer.MsgTypePB.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型，心跳，业务还是GPS上报
       * </pre>
       *
       * <code>.MsgType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int command_ ;
      /**
       * <pre>
       *区分哪个api业务系统与相应的app约定
       * </pre>
       *
       * <code>int32 command = 3;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <pre>
       *区分哪个api业务系统与相应的app约定
       * </pre>
       *
       * <code>int32 command = 3;</code>
       */
      public Builder setCommand(int value) {
        
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区分哪个api业务系统与相应的app约定
       * </pre>
       *
       * <code>int32 command = 3;</code>
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientSN_ = "";
      /**
       * <pre>
       *客户端识别码
       * </pre>
       *
       * <code>string clientSN = 4;</code>
       */
      public java.lang.String getClientSN() {
        java.lang.Object ref = clientSN_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSN_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端识别码
       * </pre>
       *
       * <code>string clientSN = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClientSNBytes() {
        java.lang.Object ref = clientSN_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSN_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端识别码
       * </pre>
       *
       * <code>string clientSN = 4;</code>
       */
      public Builder setClientSN(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSN_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端识别码
       * </pre>
       *
       * <code>string clientSN = 4;</code>
       */
      public Builder clearClientSN() {
        
        clientSN_ = getDefaultInstance().getClientSN();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端识别码
       * </pre>
       *
       * <code>string clientSN = 4;</code>
       */
      public Builder setClientSNBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSN_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appClientID_ = "";
      /**
       * <pre>
       *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
       * </pre>
       *
       * <code>string appClientID = 5;</code>
       */
      public java.lang.String getAppClientID() {
        java.lang.Object ref = appClientID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appClientID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
       * </pre>
       *
       * <code>string appClientID = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppClientIDBytes() {
        java.lang.Object ref = appClientID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appClientID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
       * </pre>
       *
       * <code>string appClientID = 5;</code>
       */
      public Builder setAppClientID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appClientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
       * </pre>
       *
       * <code>string appClientID = 5;</code>
       */
      public Builder clearAppClientID() {
        
        appClientID_ = getDefaultInstance().getAppClientID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *与服务端约定，格式为：业务平台名-客户端名，如tubobo-rider
       * </pre>
       *
       * <code>string appClientID = 5;</code>
       */
      public Builder setAppClientIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appClientID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object platformID_ = "";
      /**
       * <pre>
       *服务端平台名如tubobo
       * </pre>
       *
       * <code>string platformID = 6;</code>
       */
      public java.lang.String getPlatformID() {
        java.lang.Object ref = platformID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platformID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *服务端平台名如tubobo
       * </pre>
       *
       * <code>string platformID = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformIDBytes() {
        java.lang.Object ref = platformID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platformID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *服务端平台名如tubobo
       * </pre>
       *
       * <code>string platformID = 6;</code>
       */
      public Builder setPlatformID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platformID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务端平台名如tubobo
       * </pre>
       *
       * <code>string platformID = 6;</code>
       */
      public Builder clearPlatformID() {
        
        platformID_ = getDefaultInstance().getPlatformID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务端平台名如tubobo
       * </pre>
       *
       * <code>string platformID = 6;</code>
       */
      public Builder setPlatformIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platformID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reqID_ = "";
      /**
       * <pre>
       *请求编号
       * </pre>
       *
       * <code>string reqID = 7;</code>
       */
      public java.lang.String getReqID() {
        java.lang.Object ref = reqID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求编号
       * </pre>
       *
       * <code>string reqID = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReqIDBytes() {
        java.lang.Object ref = reqID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求编号
       * </pre>
       *
       * <code>string reqID = 7;</code>
       */
      public Builder setReqID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求编号
       * </pre>
       *
       * <code>string reqID = 7;</code>
       */
      public Builder clearReqID() {
        
        reqID_ = getDefaultInstance().getReqID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求编号
       * </pre>
       *
       * <code>string reqID = 7;</code>
       */
      public Builder setReqIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqID_ = value;
        onChanged();
        return this;
      }

      private int direction_ = 0;
      /**
       * <pre>
       *区分是请求、响应或推送
       * </pre>
       *
       * <code>.Direction direction = 8;</code>
       */
      public int getDirectionValue() {
        return direction_;
      }
      /**
       * <pre>
       *区分是请求、响应或推送
       * </pre>
       *
       * <code>.Direction direction = 8;</code>
       */
      public Builder setDirectionValue(int value) {
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区分是请求、响应或推送
       * </pre>
       *
       * <code>.Direction direction = 8;</code>
       */
      public com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction getDirection() {
        com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction result = com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.valueOf(direction_);
        return result == null ? com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *区分是请求、响应或推送
       * </pre>
       *
       * <code>.Direction direction = 8;</code>
       */
      public Builder setDirection(com.xinguang.msgprotocol.client.transfer.DirectionPB.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区分是请求、响应或推送
       * </pre>
       *
       * <code>.Direction direction = 8;</code>
       */
      public Builder clearDirection() {
        
        direction_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token值，需要登陆后才能
       * </pre>
       *
       * <code>string token = 9;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token值，需要登陆后才能
       * </pre>
       *
       * <code>string token = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token值，需要登陆后才能
       * </pre>
       *
       * <code>string token = 9;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值，需要登陆后才能
       * </pre>
       *
       * <code>string token = 9;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token值，需要登陆后才能
       * </pre>
       *
       * <code>string token = 9;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 16;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 16;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 16;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MCProtocol)
    }

    // @@protoc_insertion_point(class_scope:MCProtocol)
    private static final com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol();
    }

    public static com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MCProtocol>
        PARSER = new com.google.protobuf.AbstractParser<MCProtocol>() {
      public MCProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MCProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MCProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MCProtocol> getParserForType() {
      return PARSER;
    }

    public com.xinguang.msgprotocol.client.transfer.MCProtocolPB.MCProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MCProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MCProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MCProtocol.proto\032\rMsgType.proto\032\017Direc" +
      "tion.proto\"\314\001\n\nMCProtocol\022\017\n\007version\030\001 \001" +
      "(\t\022\026\n\004type\030\002 \001(\0162\010.MsgType\022\017\n\007command\030\003 " +
      "\001(\005\022\020\n\010clientSN\030\004 \001(\t\022\023\n\013appClientID\030\005 \001" +
      "(\t\022\022\n\nplatformID\030\006 \001(\t\022\r\n\005reqID\030\007 \001(\t\022\035\n" +
      "\tdirection\030\010 \001(\0162\n.Direction\022\r\n\005token\030\t " +
      "\001(\t\022\014\n\004body\030\020 \001(\014B8\n(com.xinguang.msgpro" +
      "tocol.client.transferB\014MCProtocolPBb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xinguang.msgprotocol.client.transfer.MsgTypePB.getDescriptor(),
          com.xinguang.msgprotocol.client.transfer.DirectionPB.getDescriptor(),
        }, assigner);
    internal_static_MCProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MCProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MCProtocol_descriptor,
        new java.lang.String[] { "Version", "Type", "Command", "ClientSN", "AppClientID", "PlatformID", "ReqID", "Direction", "Token", "Body", });
    com.xinguang.msgprotocol.client.transfer.MsgTypePB.getDescriptor();
    com.xinguang.msgprotocol.client.transfer.DirectionPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
