// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MCResponse.proto

package com.xinguang.msgprotocol.client.transfer;

public final class MCResponsePB {
  private MCResponsePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MCResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MCResultCode resultCode = 1;</code>
     */
    int getResultCodeValue();
    /**
     * <code>.MCResultCode resultCode = 1;</code>
     */
    com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode getResultCode();

    /**
     * <code>bytes resultData = 2;</code>
     */
    com.google.protobuf.ByteString getResultData();

    /**
     * <code>string resultDesc = 3;</code>
     */
    java.lang.String getResultDesc();
    /**
     * <code>string resultDesc = 3;</code>
     */
    com.google.protobuf.ByteString
        getResultDescBytes();
  }
  /**
   * Protobuf type {@code MCResponse}
   */
  public  static final class MCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MCResponse)
      MCResponseOrBuilder {
    // Use MCResponse.newBuilder() to construct.
    private MCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MCResponse() {
      resultCode_ = 0;
      resultData_ = com.google.protobuf.ByteString.EMPTY;
      resultDesc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              resultCode_ = rawValue;
              break;
            }
            case 18: {

              resultData_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              resultDesc_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.msgprotocol.client.transfer.MCResponsePB.internal_static_MCResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.msgprotocol.client.transfer.MCResponsePB.internal_static_MCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.class, com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.Builder.class);
    }

    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>.MCResultCode resultCode = 1;</code>
     */
    public int getResultCodeValue() {
      return resultCode_;
    }
    /**
     * <code>.MCResultCode resultCode = 1;</code>
     */
    public com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode getResultCode() {
      com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode result = com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.valueOf(resultCode_);
      return result == null ? com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.UNRECOGNIZED : result;
    }

    public static final int RESULTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString resultData_;
    /**
     * <code>bytes resultData = 2;</code>
     */
    public com.google.protobuf.ByteString getResultData() {
      return resultData_;
    }

    public static final int RESULTDESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object resultDesc_;
    /**
     * <code>string resultDesc = 3;</code>
     */
    public java.lang.String getResultDesc() {
      java.lang.Object ref = resultDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string resultDesc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResultDescBytes() {
      java.lang.Object ref = resultDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultCode_ != com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.SUCCESS.getNumber()) {
        output.writeEnum(1, resultCode_);
      }
      if (!resultData_.isEmpty()) {
        output.writeBytes(2, resultData_);
      }
      if (!getResultDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resultDesc_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultCode_ != com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_);
      }
      if (!resultData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, resultData_);
      }
      if (!getResultDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resultDesc_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse)) {
        return super.equals(obj);
      }
      com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse other = (com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse) obj;

      boolean result = true;
      result = result && resultCode_ == other.resultCode_;
      result = result && getResultData()
          .equals(other.getResultData());
      result = result && getResultDesc()
          .equals(other.getResultDesc());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + resultCode_;
      hash = (37 * hash) + RESULTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getResultData().hashCode();
      hash = (37 * hash) + RESULTDESC_FIELD_NUMBER;
      hash = (53 * hash) + getResultDesc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MCResponse)
        com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.msgprotocol.client.transfer.MCResponsePB.internal_static_MCResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.msgprotocol.client.transfer.MCResponsePB.internal_static_MCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.class, com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.Builder.class);
      }

      // Construct using com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resultCode_ = 0;

        resultData_ = com.google.protobuf.ByteString.EMPTY;

        resultDesc_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.msgprotocol.client.transfer.MCResponsePB.internal_static_MCResponse_descriptor;
      }

      public com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse getDefaultInstanceForType() {
        return com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.getDefaultInstance();
      }

      public com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse build() {
        com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse buildPartial() {
        com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse result = new com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse(this);
        result.resultCode_ = resultCode_;
        result.resultData_ = resultData_;
        result.resultDesc_ = resultDesc_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse) {
          return mergeFrom((com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse other) {
        if (other == com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse.getDefaultInstance()) return this;
        if (other.resultCode_ != 0) {
          setResultCodeValue(other.getResultCodeValue());
        }
        if (other.getResultData() != com.google.protobuf.ByteString.EMPTY) {
          setResultData(other.getResultData());
        }
        if (!other.getResultDesc().isEmpty()) {
          resultDesc_ = other.resultDesc_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resultCode_ = 0;
      /**
       * <code>.MCResultCode resultCode = 1;</code>
       */
      public int getResultCodeValue() {
        return resultCode_;
      }
      /**
       * <code>.MCResultCode resultCode = 1;</code>
       */
      public Builder setResultCodeValue(int value) {
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MCResultCode resultCode = 1;</code>
       */
      public com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode getResultCode() {
        com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode result = com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.valueOf(resultCode_);
        return result == null ? com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.MCResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(com.xinguang.msgprotocol.client.transfer.MCResultCodePB.MCResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resultCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MCResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString resultData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes resultData = 2;</code>
       */
      public com.google.protobuf.ByteString getResultData() {
        return resultData_;
      }
      /**
       * <code>bytes resultData = 2;</code>
       */
      public Builder setResultData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes resultData = 2;</code>
       */
      public Builder clearResultData() {
        
        resultData_ = getDefaultInstance().getResultData();
        onChanged();
        return this;
      }

      private java.lang.Object resultDesc_ = "";
      /**
       * <code>string resultDesc = 3;</code>
       */
      public java.lang.String getResultDesc() {
        java.lang.Object ref = resultDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resultDesc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResultDescBytes() {
        java.lang.Object ref = resultDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resultDesc = 3;</code>
       */
      public Builder setResultDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resultDesc = 3;</code>
       */
      public Builder clearResultDesc() {
        
        resultDesc_ = getDefaultInstance().getResultDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string resultDesc = 3;</code>
       */
      public Builder setResultDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultDesc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MCResponse)
    }

    // @@protoc_insertion_point(class_scope:MCResponse)
    private static final com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse();
    }

    public static com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MCResponse>
        PARSER = new com.google.protobuf.AbstractParser<MCResponse>() {
      public MCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MCResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MCResponse> getParserForType() {
      return PARSER;
    }

    public com.xinguang.msgprotocol.client.transfer.MCResponsePB.MCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MCResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MCResponse.proto\032\022MCResultCode.proto\"W" +
      "\n\nMCResponse\022!\n\nresultCode\030\001 \001(\0162\r.MCRes" +
      "ultCode\022\022\n\nresultData\030\002 \001(\014\022\022\n\nresultDes" +
      "c\030\003 \001(\tB8\n(com.xinguang.msgprotocol.clie" +
      "nt.transferB\014MCResponsePBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xinguang.msgprotocol.client.transfer.MCResultCodePB.getDescriptor(),
        }, assigner);
    internal_static_MCResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MCResponse_descriptor,
        new java.lang.String[] { "ResultCode", "ResultData", "ResultDesc", });
    com.xinguang.msgprotocol.client.transfer.MCResultCodePB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
